// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { TCMPopStar, TCMPopStarData, TCMPopStarTableId } from "./tables/TCMPopStar.sol";
import { TokenBalance, TokenBalanceTableId } from "./tables/TokenBalance.sol";
import { TokenSold, TokenSoldData, TokenSoldTableId } from "./tables/TokenSold.sol";
import { GameSuccess, GameSuccessData, GameSuccessTableId } from "./tables/GameSuccess.sol";
