// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { DefaultParameters } from "./../../core_codegen/index.sol";

/**
 * @title IMyAppSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMyAppSystem {
  function myapp_MyAppSystem_init() external;

  function myapp_MyAppSystem_interact(DefaultParameters memory default_parameters) external;
}
